version: "3.7"
services:
  discord-bot:
    build:
      context: .
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      SPREADSHEET_ID: ${SPREADSHEET_ID}
      ENV: ${ENV}